/**
 * Generates `docs/ERRORS.md` from the diagnostic registry in `src/codes.ts`.
 *
 *   node scripts/generate-error-docs.ts            # print
 *   node scripts/generate-error-docs.ts --write    # rewrite the file
 *
 * `test/codes.test.ts` fails if the committed file differs, so the reference
 * cannot drift away from the codes the compiler actually emits.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import process from "node:process";

import { DIAGNOSTIC_CODES, allCodes } from "../src/codes.ts";

export const DOC_PATH = fileURLToPath(new URL("../docs/ERRORS.md", import.meta.url));

const GROUPS: Array<[prefix: string, title: string]> = [
  ["E01", "Lexical"],
  ["E02", "Syntax"],
  ["E03", "Names and scope"],
  ["E04", "Control flow"],
  ["E05", "Types and operations"],
  ["E06", "Limits"],
  ["W09", "Warnings"],
];

export function renderErrorDocs(): string {
  const out: string[] = [];

  out.push("# Diagnostic reference");
  out.push("");
  out.push(
    "Every Luma diagnostic carries a stable code. Messages may be reworded; codes never",
    "change, and a retired code is never reused — so a link to one keeps meaning what it",
    "meant.",
  );
  out.push("");
  out.push("Run `luma explain <CODE>` to print any of these from the command line.");
  out.push("");
  out.push("<!-- Generated by scripts/generate-error-docs.ts. Do not edit by hand. -->");
  out.push("");

  out.push("| Code | Meaning |");
  out.push("| --- | --- |");
  for (const code of allCodes()) {
    out.push(`| [\`${code}\`](#${code.toLowerCase()}) | ${DIAGNOSTIC_CODES[code].title} |`);
  }
  out.push("");

  for (const [prefix, title] of GROUPS) {
    const codes = allCodes().filter((code) => code.startsWith(prefix));
    if (codes.length === 0) continue;

    out.push(`## ${title}`);
    out.push("");
    for (const code of codes) {
      const entry = DIAGNOSTIC_CODES[code];
      out.push(`### ${code}`);
      out.push("");
      out.push(`**${entry.title}**`);
      out.push("");
      out.push(entry.explanation);
      out.push("");
    }
  }

  return `${out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd()}\n`;
}

export function readErrorDocs(): string | null {
  try {
    return readFileSync(DOC_PATH, "utf8");
  } catch {
    return null;
  }
}

const invokedDirectly =
  process.argv[1] !== undefined &&
  fileURLToPath(import.meta.url).endsWith(process.argv[1].replace(/^.*[/\\]/, ""));

if (invokedDirectly) {
  const rendered = renderErrorDocs();
  if (process.argv.includes("--write")) {
    writeFileSync(DOC_PATH, rendered, "utf8");
    process.stdout.write(`wrote ${DOC_PATH}\n`);
  } else {
    process.stdout.write(rendered);
  }
}
